### ISSUE TITLE
survey.Input input is removed after validation 

### ISSUE THREAD

**Issue by Nicocha30** [AlecAivazis/survey#310]
**What operating system and terminal are you using?**

Fedora 31, tested with Tilix (zsh) and Gnome Terminal (bash). 

**An example that showcases the bug.**

Using the *examples/simple.go* file, after writing the first answer and hitting the Return key, my input is removed.

![surveyissue](https://user-images.githubusercontent.com/31402213/98383159-6a6c0700-204c-11eb-936c-3a748611128e.gif)

**What did you expect to see?**

The same behavior as the example on the README

![image](https://camo.githubusercontent.com/7c8d7a77e23a669bb32c590d93cf4237a2cd5515/68747470733a2f2f7468756d62732e6766796361742e636f6d2f56696c6c61696e6f757347726163696f75734b6f75707265792d73697a655f726573747269637465642e676966)

Thanks a lot,

Nicolas

**Comment by AlecAivazis** [comment]
Hey @Nicocha30! thanks for bringing this up, we recently merged in a nice update to the inputs and apparently i missed this. 

I'll get a fix in right now :)

**Comment by AlecAivazis** [comment]
This should now be fixed and released as part of `v2.2.2`. please let me know if you still run into this

**Comment by samcoe** [comment]
Just wanted to add a note here saying that this issue still seems to be present in v2.2.2, it was reported by one of our users [here](https://github.com/cli/cli/issues/2417).

**Comment by AlecAivazis** [comment]
Hey @samcoe thanks for bringing this up. I'm going to reopen the issue so i dont forget.

**Comment by AlecAivazis** [comment]
@samcoe this should now be fixed in `v2.2.3`. Thanks again for bringing it up and being patient

**Comment by samcoe** [comment]
@AlecAivazis thanks for the rapid fix! 🙇
